# Allow compute credits usage for collaborators and anything pushed to the
# main, staging, and trying branches. (So bors can use them.)
#use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true' || $CIRRUS_BRANCH == 'main' || $CIRRUS_BRANCH == 'staging' || $CIRRUS_BRANCH == 'trying'

task:
  only_if: $BRANCH != 'main'
  name: CI success
  container: {image: "busybox"}
  depends_on:
    - test

test_task:
  only_if: $BRANCH != 'main'
  container:
    image: debian:latest
  install_script:
    - apt update && apt install -y make git curl unzip
    - make ci-setup
  script:
    - make test

release_task:
  only_if: $BRANCH == 'main'
  env:
    BUTLER_API_KEY: ENCRYPTED[46a314af5ccb389fce4671b233802ae05d7f554aaa0a13102c6d908b8b824416c4308cfb61c7271a3bb8e25b0463f23d]
    DISCORD_WEBHOOK: ENCRYPTED[9b192e26cda882699806de29d5453a5f2b97011a65a3cfd52ab0906e24a7c19b65bfd6dfe7309acf0e499a58e85df162]
  container:
    dockerfile: ci/Dockerfile
  tools_cache:
    folder: tools
    fingerprint_script:
      - cat Makefile
    populate_script:
      - make tools/godot tools/butler
  template_cache:
    folder: ${HOME}/.local/share/godot/export_templates
    fingerprint_script:
      - cat Makefile
    populate_script:
      make godot-templates
  install_script:
    - make ci-setup
  build_script:
    matrix:
      - make linux
      - make windows
      - make macos
  release_script:
    matrix:
      - ./tools/butler push build/linux duckinator/keress:linux --userversion-file src/version.txt
      - ./tools/butler push build/windows duckinator/keress:windows --userversion-file src/version.txt
      - ./tools/butler push build/mac duckinator/keress:mac --userversion-file src/version.txt
  script:
    - python3 bin/ci-announce-release.py
