test_task:
  container:
    image: duckinator/godot-builder:latest
  install_script:
    - make ci-setup
  script:
    - make test

nightly_task:
  only_if: $BRANCH == 'nightly'
  env:
    BUTLER_API_KEY: ENCRYPTED[46a314af5ccb389fce4671b233802ae05d7f554aaa0a13102c6d908b8b824416c4308cfb61c7271a3bb8e25b0463f23d]
  #depends_on:
  #  - test
  container:
    image: duckinator/godot-builder:latest
  install_script:
    - make ci-setup
  script:
    - make release
    - butler push build/linux duckinator/keress:linux-nightly
    - butler push build/windows duckinator/keress:windows-nightly
    - butler push build/mac duckinator/keress:mac-nightly
