Linux_task:
  container:
    image: debian:9-slim
  install_script:
    - apt-get update -yq
    - apt-get install -yq git make curl zip unzip
    - make ci-setup
  script:
    - make
    - make ci-nightly

