test_task:
  container:
    image: debian:9-slim
  install_script:
    - apt-get update -yq
    - apt-get install -yq git make curl zip unzip
    - make ci-setup
  script:
    - make test

nightly_task:
  only_if: $BRANCH == 'nightly'
  #depends_on:
  #  - test
  container:
    image: debian:9-slim
  install_script:
    - apt-get update -yq
    - apt-get install -yq git make curl zip unzip
    - make ci-setup
  script:
    - make ci-nightly
