# Allow compute credits usage for collaborators and anything pushed to the
# main, staging, and trying branches. (So bors can use them.)
use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true' || $CIRRUS_BRANCH == 'main' || $CIRRUS_BRANCH == 'staging' || $CIRRUS_BRANCH == 'trying'

task:
  name: CI success
  container: {image: "busybox"}
  depends_on:
    - test

test_task:
  container:
    dockerfile: ci/Dockerfile
  install_script:
    - make ci-setup
  script:
    - make test

release_task:
  only_if: $BRANCH == 'main'
  depends_on:
    - test
  env:
    BUTLER_API_KEY: ENCRYPTED[46a314af5ccb389fce4671b233802ae05d7f554aaa0a13102c6d908b8b824416c4308cfb61c7271a3bb8e25b0463f23d]
    DISCORD_WEBHOOK: ENCRYPTED[fdae29c84d2f19dfd5419efcd72d5017bb23d8e3b83cc81e2c0723c4d00e5bde787a5b481640f6b422c5e60d2faee3bc]
  container:
    dockerfile: ci/Dockerfile
  install_script:
    - make ci-setup
  script:
    - make release
    - butler push build/linux duckinator/keress:linux --userversion-file src/version.txt
    - butler push build/windows duckinator/keress:windows --userversion-file src/version.txt
    - butler push build/mac duckinator/keress:mac --userversion-file src/version.txt
    - python3 bin/ci-announce-release.py
